// GENERATED by tools/gen-boards.mjs from schema/hardware.json — do not edit.
//
// Tier 1 - Baseline carrier: 4 header-connected modules, 17 signals.
//
// This is a reference carrier that has never been fabricated. It exists so the
// pin assignments in the hardware registry are checked by a router rather than
// by a reader. Do not send these outputs to a fab without reviewing them.
//
// Modules on this board:
//   J2  gnss-lc29h       uart+gpio
//   J3  env-bme688       i2c
//   J4  imu-bno085       i2c
//   J5  lwir-mlx90640    i2c
//
// Not on this board: USB peripherals and CSI cameras, which do not touch the
// GPIO header. See schema/hardware.json for the full tier bill of materials.

export default () => (
  <board
    width="65mm"
    height="56mm"
    /* Four layers. Two could not route tier 3's 37 nets, and a carrier with
       this many buses crossing wants an inner ground plane anyway. */
    layers={4}
    /* The default capacity-mesh autorouter throws on this netlist in the
       currently pinned CLI, and does so while the export still reports
       success. Pinned to the sequential router, and tools/check-boards.mjs
       fails the build if the trace count ever comes back short. */
    autorouter="sequential-trace"
  >
    {/* Raspberry Pi 5 40-pin GPIO header. Pin numbering is physical, matching
        the "pin" field in schema/hardware.json. */}
    <pinheader
      name="J1"
      pinCount={40}
      gender="male"
      pitch="2.54mm"
      doubleRow
      pcbX={0} pcbY={-21} schX={-9} schY={0}
    />

    {/* gnss-lc29h — Quectel / Waveshare LC29H(DA) RTK HAT with PPS (uart+gpio) */}
    <pinheader
      name="J2"
      pinCount={5}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"TXD__RXD","pin4":"RXD__TXD","pin5":"PPS"}}
      pcbX={-19} pcbY={20} schX={0} schY={4}
    />
    {/* env-bme688 — Bosch BME688 (i2c) */}
    <pinheader
      name="J3"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={15} pcbY={20} schX={7} schY={4}
    />
    {/* imu-bno085 — CEVA / Adafruit BNO085 9-DoF IMU (i2c) */}
    <pinheader
      name="J4"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-19} pcbY={10} schX={0} schY={0}
    />
    {/* lwir-mlx90640 — Melexis MLX90640 32x24 thermal array (i2c) */}
    <pinheader
      name="J5"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={15} pcbY={10} schX={7} schY={0}
    />

    <net name="V33" />
    <net name="GND" />
    <trace from=".J2 > .3V3" to="net.V33" />
    <trace from=".J3 > .3V3" to="net.V33" />
    <trace from=".J4 > .3V3" to="net.V33" />
    <trace from=".J5 > .3V3" to="net.V33" />
    <trace from=".J1 > .pin1" to="net.V33" />
    <trace from=".J1 > .pin17" to="net.V33" />
    <trace from=".J2 > .GND" to="net.GND" />
    <trace from=".J3 > .GND" to="net.GND" />
    <trace from=".J4 > .GND" to="net.GND" />
    <trace from=".J5 > .GND" to="net.GND" />
    <trace from=".J1 > .pin6" to="net.GND" />
    <trace from=".J1 > .pin9" to="net.GND" />
    <trace from=".J2 > .TXD__RXD" to=".J1 > .pin10" />
    <trace from=".J2 > .RXD__TXD" to=".J1 > .pin8" />
    <trace from=".J2 > .PPS" to=".J1 > .pin7" />
    <trace from=".J3 > .SDA" to=".J1 > .pin3" />
    <trace from=".J3 > .SCL" to=".J1 > .pin5" />
    <trace from=".J4 > .SDA" to=".J1 > .pin3" />
    <trace from=".J4 > .SCL" to=".J1 > .pin5" />
    <trace from=".J5 > .SDA" to=".J1 > .pin3" />
    <trace from=".J5 > .SCL" to=".J1 > .pin5" />
  </board>
)
