// GENERATED by tools/gen-boards.mjs from schema/hardware.json — do not edit.
//
// Tier 1 - Baseline carrier: 4 header-connected modules, 17 signals.
//
// This is a reference carrier that has never been fabricated. It exists so the
// pin assignments in the hardware registry are checked by a router rather than
// by a reader. Do not send these outputs to a fab without reviewing them.
//
// Modules on this board:
//   J2  env-bme688       i2c
//   J3  lwir-mlx90640    i2c
//   J4  imu-bno085       i2c
//   J5  gnss-lc29h       uart+gpio
//
// Not on this board: USB peripherals and CSI cameras, which do not touch the
// GPIO header. See schema/hardware.json for the full tier bill of materials.

export default () => (
  <board
    width="90mm"
    height="56mm"
    /* Four layers. Two could not route tier 3's 37 nets, and a carrier with
       this many buses crossing wants an inner ground plane anyway. */
    layers={4}
    /* The default autorouter, capacity-mesh. It used to throw on these
       netlists — and print "Exported!" while doing it — because the CLI runs
       under Bun and Bun 1.1.18 lacks the ES2025 Iterator Helpers its solver
       calls. hardware/iterator-helpers-polyfill.js supplies them via
       bun --preload. Falling back to the sequential router instead had cost
       roughly a quarter of the nets. */
  >
    {/* Raspberry Pi 5 40-pin GPIO header. Pin numbering is physical, matching
        the "pin" field in schema/hardware.json. */}
    {/* Pins are labelled P1..P40 by Raspberry Pi physical number. The
        connector's own numbering is counter-clockwise and does not match; see
        piPinToHeaderIndex in tools/gen-boards.mjs. Everything below references
        the P-labels, never the connector index. */}
    <pinheader
      name="J1"
      pinCount={40}
      gender="male"
      pitch="2.54mm"
      doubleRow
      pinLabels={{"pin1":"P1","pin2":"P2","pin40":"P3","pin3":"P4","pin39":"P5","pin4":"P6","pin38":"P7","pin5":"P8","pin37":"P9","pin6":"P10","pin36":"P11","pin7":"P12","pin35":"P13","pin8":"P14","pin34":"P15","pin9":"P16","pin33":"P17","pin10":"P18","pin32":"P19","pin11":"P20","pin31":"P21","pin12":"P22","pin30":"P23","pin13":"P24","pin29":"P25","pin14":"P26","pin28":"P27","pin15":"P28","pin27":"P29","pin16":"P30","pin26":"P31","pin17":"P32","pin25":"P33","pin18":"P34","pin24":"P35","pin19":"P36","pin23":"P37","pin20":"P38","pin22":"P39","pin21":"P40"}}
      pcbX={-0.87} pcbY={23.23} schX={-9} schY={0}
    />

    {/* env-bme688 — Bosch BME688 (i2c) */}
    <pinheader
      name="J2"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-20.32} pcbY={14.23} schX={0} schY={4}
    />
    {/* lwir-mlx90640 — Melexis MLX90640 32x24 thermal array (i2c) */}
    <pinheader
      name="J3"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-8.16} pcbY={14.23} schX={7} schY={4}
    />
    {/* imu-bno085 — CEVA / Adafruit BNO085 9-DoF IMU (i2c) */}
    <pinheader
      name="J4"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-20.32} pcbY={4.73} schX={0} schY={0}
    />
    {/* gnss-lc29h — Quectel / Waveshare LC29H(DA) RTK HAT with PPS (uart+gpio) */}
    <pinheader
      name="J5"
      pinCount={5}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"TXD__RXD","pin4":"RXD__TXD","pin5":"PPS"}}
      pcbX={-6.89} pcbY={4.73} schX={7} schY={0}
    />

    <net name="SDA" />
    <net name="SCL" />
    <net name="V33" />
    <net name="GND" />
    <copperpour layer="inner1" connectsTo="net.GND" />
    <hole name="H1" diameter="2.75mm" pcbX={-29} pcbY={-24.5} />
    <hole name="H2" diameter="2.75mm" pcbX={29} pcbY={-24.5} />
    <hole name="H3" diameter="2.75mm" pcbX={-29} pcbY={24.5} />
    <hole name="H4" diameter="2.75mm" pcbX={29} pcbY={24.5} />
    {/* decoupling for J2 (env-bme688) */}
    <capacitor name="C1" capacitance="100nF" footprint="0402"
      pcbX={-19.32} pcbY={10.63} schX={0} schY={2.4} />
    {/* decoupling for J3 (lwir-mlx90640) */}
    <capacitor name="C2" capacitance="100nF" footprint="0402"
      pcbX={-7.16} pcbY={10.63} schX={7} schY={2.4} />
    {/* decoupling for J4 (imu-bno085) */}
    <capacitor name="C3" capacitance="100nF" footprint="0402"
      pcbX={-19.32} pcbY={1.13} schX={0} schY={-1.6} />
    {/* decoupling for J5 (gnss-lc29h) */}
    <capacitor name="C4" capacitance="100nF" footprint="0402"
      pcbX={-5.89} pcbY={1.13} schX={7} schY={-1.6} />
    {/* bulk reservoir on V33 */}
    <capacitor name="C5" capacitance="10uF" footprint="0805"
      pcbX={-19.00} pcbY={-15.77} schX={-4} schY={-15} />
    {/* TVS clamp on SDA, which leaves the enclosure toward
        env-bme688. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D1" footprint="sot23" pcbX={-41.50} pcbY={-9.77}
      schX={0} schY={1.6} />
    {/* TVS clamp on SCL, which leaves the enclosure toward
        env-bme688. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D2" footprint="sot23" pcbX={-36.00} pcbY={-9.77}
      schX={0} schY={1.6} />
    {/* V33 supply: resettable fuse and reverse-polarity diode. An
        off-grid node is wired by whoever installed it, in the field,
        often in the dark, and battery leads get reversed. */}
    <fuse name="F1" currentRating="2A" footprint="1206"
      pcbX={-30.50} pcbY={-9.77} schX={-6} schY={-9} />
    <diode name="D3" footprint="sod123"
      pcbX={-25.50} pcbY={-9.77} schX={-4} schY={-9} />
    <trace from=".J2 > .SDA" to="net.SDA" />
    <trace from=".J3 > .SDA" to="net.SDA" />
    <trace from=".J4 > .SDA" to="net.SDA" />
    <trace from=".J1 > .P3" to="net.SDA" />
    <trace from=".J2 > .SCL" to="net.SCL" />
    <trace from=".J3 > .SCL" to="net.SCL" />
    <trace from=".J4 > .SCL" to="net.SCL" />
    <trace from=".J1 > .P5" to="net.SCL" />
    <trace from=".J2 > .3V3" to="net.V33" />
    <trace from=".J3 > .3V3" to="net.V33" />
    <trace from=".J4 > .3V3" to="net.V33" />
    <trace from=".J5 > .3V3" to="net.V33" />
    <trace from=".J1 > .P17" to="net.V33" />
    <trace from=".J1 > .P1" to="net.V33" />
    <trace from=".J2 > .GND" to="net.GND" />
    <trace from=".J3 > .GND" to="net.GND" />
    <trace from=".J4 > .GND" to="net.GND" />
    <trace from=".J5 > .GND" to="net.GND" />
    <trace from=".J1 > .P9" to="net.GND" />
    <trace from=".J1 > .P6" to="net.GND" />
    <trace from=".C1 > .pin1" to="net.V33" />
    <trace from=".C1 > .pin2" to="net.GND" />
    <trace from=".C2 > .pin1" to="net.V33" />
    <trace from=".C2 > .pin2" to="net.GND" />
    <trace from=".C3 > .pin1" to="net.V33" />
    <trace from=".C3 > .pin2" to="net.GND" />
    <trace from=".C4 > .pin1" to="net.V33" />
    <trace from=".C4 > .pin2" to="net.GND" />
    <trace from=".C5 > .pin1" to="net.V33" />
    <trace from=".C5 > .pin2" to="net.GND" />
    <trace from=".D1 > .pin1" to="net.GND" />
    <trace from=".D1 > .pin2" to="net.SDA" />
    <trace from=".D2 > .pin1" to="net.GND" />
    <trace from=".D2 > .pin2" to="net.SCL" />
    <trace from=".F1 > .pin1" to="net.V33" />
    <trace from=".D3 > .pin1" to="net.GND" />
    <trace from=".J5 > .TXD__RXD" to=".J1 > .P10" />
    <trace from=".J5 > .RXD__TXD" to=".J1 > .P8" />
    <trace from=".J5 > .PPS" to=".J1 > .P7" />
  </board>
)
