// GENERATED by tools/gen-boards.mjs from schema/hardware.json — do not edit.
//
// Tier 2 - Core carrier: 8 header-connected modules, 36 signals.
//
// This is a reference carrier that has never been fabricated. It exists so the
// pin assignments in the hardware registry are checked by a router rather than
// by a reader. Do not send these outputs to a fab without reviewing them.
//
// Modules on this board:
//   J2  env-bme688       i2c
//   J3  pwr-ina226       i2c
//   J4  mic-ics43434     i2s
//   J5  imu-bno085       i2c
//   J6  gnss-lc29h       uart+gpio
//   J7  radar-ld2450     uart
//   J8  uv-as7331        i2c
//   J9  mag-rm3100       spi
//
// Not on this board: USB peripherals and CSI cameras, which do not touch the
// GPIO header. See schema/hardware.json for the full tier bill of materials.

export default () => (
  <board
    width="85mm"
    height="56mm"
    /* Four layers. Two could not route tier 3's 37 nets, and a carrier with
       this many buses crossing wants an inner ground plane anyway. */
    layers={4}
    /* The default autorouter, capacity-mesh. It used to throw on these
       netlists — and print "Exported!" while doing it — because the CLI runs
       under Bun and Bun 1.1.18 lacks the ES2025 Iterator Helpers its solver
       calls. hardware/iterator-helpers-polyfill.js supplies them via
       bun --preload. Falling back to the sequential router instead had cost
       roughly a quarter of the nets. */
  >
    {/* Raspberry Pi 5 40-pin GPIO header. Pin numbering is physical, matching
        the "pin" field in schema/hardware.json. */}
    {/* Pins are labelled P1..P40 by Raspberry Pi physical number. The
        connector's own numbering is counter-clockwise and does not match; see
        piPinToHeaderIndex in tools/gen-boards.mjs. Everything below references
        the P-labels, never the connector index. */}
    <pinheader
      name="J1"
      pinCount={40}
      gender="male"
      pitch="2.54mm"
      doubleRow
      pinLabels={{"pin1":"P1","pin2":"P2","pin40":"P3","pin3":"P4","pin39":"P5","pin4":"P6","pin38":"P7","pin5":"P8","pin37":"P9","pin6":"P10","pin36":"P11","pin7":"P12","pin35":"P13","pin8":"P14","pin34":"P15","pin9":"P16","pin33":"P17","pin10":"P18","pin32":"P19","pin11":"P20","pin31":"P21","pin12":"P22","pin30":"P23","pin13":"P24","pin29":"P25","pin14":"P26","pin28":"P27","pin15":"P28","pin27":"P29","pin16":"P30","pin26":"P31","pin17":"P32","pin25":"P33","pin18":"P34","pin24":"P35","pin19":"P36","pin23":"P37","pin20":"P38","pin22":"P39","pin21":"P40"}}
      pcbX={0} pcbY={-21} schX={-9} schY={0}
    />

    {/* env-bme688 — Bosch BME688 (i2c) */}
    <pinheader
      name="J2"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-20.32} pcbY={22} schX={0} schY={4}
    />
    {/* pwr-ina226 — Texas Instruments / generic breakout INA226 bidirectional current and power monitor (i2c) */}
    <pinheader
      name="J3"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-8.16} pcbY={22} schX={7} schY={4}
    />
    {/* mic-ics43434 — TDK InvenSense ICS-43434 I2S MEMS microphone (i2s) */}
    <pinheader
      name="J4"
      pinCount={5}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"BCLK","pin4":"LRCL","pin5":"DOUT"}}
      pcbX={9.74} pcbY={22} schX={14} schY={4}
    />
    {/* imu-bno085 — CEVA / Adafruit BNO085 9-DoF IMU (i2c) */}
    <pinheader
      name="J5"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-20.32} pcbY={12.5} schX={0} schY={0}
    />
    {/* gnss-lc29h — Quectel / Waveshare LC29H(DA) RTK HAT with PPS (uart+gpio) */}
    <pinheader
      name="J6"
      pinCount={5}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"TXD__RXD","pin4":"RXD__TXD","pin5":"PPS"}}
      pcbX={-6.89} pcbY={12.5} schX={7} schY={0}
    />
    {/* radar-ld2450 — Hi-Link LD2450 24 GHz tracking radar (uart) */}
    <pinheader
      name="J7"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"5V","pin2":"GND","pin3":"TX","pin4":"RX"}}
      pcbX={15.24} pcbY={12.5} schX={14} schY={0}
    />
    {/* uv-as7331 — ams OSRAM AS7331 UVA/UVB/UVC sensor (i2c) */}
    <pinheader
      name="J8"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-20.32} pcbY={3} schX={0} schY={-4}
    />
    {/* mag-rm3100 — PNI Sensor RM3100 3-axis geomagnetic sensor (spi) */}
    <pinheader
      name="J9"
      pinCount={6}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"MOSI","pin4":"MISO","pin5":"SCLK","pin6":"CS"}}
      pcbX={1.91} pcbY={3} schX={7} schY={-4}
    />

    <net name="SDA" />
    <net name="SCL" />
    <net name="V33" />
    <net name="GND" />
    <net name="V5" />
    <copperpour layer="inner1" connectsTo="net.GND" />
    <hole name="H1" diameter="2.75mm" pcbX={-29} pcbY={-24.5} />
    <hole name="H2" diameter="2.75mm" pcbX={29} pcbY={-24.5} />
    <hole name="H3" diameter="2.75mm" pcbX={-29} pcbY={24.5} />
    <hole name="H4" diameter="2.75mm" pcbX={29} pcbY={24.5} />
    {/* decoupling for J2 (env-bme688) */}
    <capacitor name="C1" capacitance="100nF" footprint="0402"
      pcbX={-19.32} pcbY={18.40} schX={0} schY={2.4} />
    {/* decoupling for J3 (pwr-ina226) */}
    <capacitor name="C2" capacitance="100nF" footprint="0402"
      pcbX={-7.16} pcbY={18.40} schX={7} schY={2.4} />
    {/* decoupling for J4 (mic-ics43434) */}
    <capacitor name="C3" capacitance="100nF" footprint="0402"
      pcbX={10.74} pcbY={18.40} schX={14} schY={2.4} />
    {/* decoupling for J5 (imu-bno085) */}
    <capacitor name="C4" capacitance="100nF" footprint="0402"
      pcbX={-19.32} pcbY={8.90} schX={0} schY={-1.6} />
    {/* decoupling for J6 (gnss-lc29h) */}
    <capacitor name="C5" capacitance="100nF" footprint="0402"
      pcbX={-5.89} pcbY={8.90} schX={7} schY={-1.6} />
    {/* decoupling for J7 (radar-ld2450) */}
    <capacitor name="C6" capacitance="100nF" footprint="0402"
      pcbX={16.24} pcbY={8.90} schX={14} schY={-1.6} />
    {/* decoupling for J8 (uv-as7331) */}
    <capacitor name="C7" capacitance="100nF" footprint="0402"
      pcbX={-19.32} pcbY={-0.60} schX={0} schY={-5.6} />
    {/* decoupling for J9 (mag-rm3100) */}
    <capacitor name="C8" capacitance="100nF" footprint="0402"
      pcbX={2.91} pcbY={-0.60} schX={7} schY={-5.6} />
    {/* bulk reservoir on V33 */}
    <capacitor name="C9" capacitance="10uF" footprint="0805"
      pcbX={-19.00} pcbY={-11.5} schX={-4} schY={-21} />
    {/* bulk reservoir on V5 */}
    <capacitor name="C10" capacitance="10uF" footprint="0805"
      pcbX={-13.00} pcbY={-11.5} schX={-4} schY={-22.5} />
    <trace from=".J2 > .SDA" to="net.SDA" />
    <trace from=".J3 > .SDA" to="net.SDA" />
    <trace from=".J5 > .SDA" to="net.SDA" />
    <trace from=".J8 > .SDA" to="net.SDA" />
    <trace from=".J1 > .P3" to="net.SDA" />
    <trace from=".J2 > .SCL" to="net.SCL" />
    <trace from=".J3 > .SCL" to="net.SCL" />
    <trace from=".J5 > .SCL" to="net.SCL" />
    <trace from=".J8 > .SCL" to="net.SCL" />
    <trace from=".J1 > .P5" to="net.SCL" />
    <trace from=".J2 > .3V3" to="net.V33" />
    <trace from=".J3 > .3V3" to="net.V33" />
    <trace from=".J4 > .3V3" to="net.V33" />
    <trace from=".J5 > .3V3" to="net.V33" />
    <trace from=".J6 > .3V3" to="net.V33" />
    <trace from=".J8 > .3V3" to="net.V33" />
    <trace from=".J9 > .3V3" to="net.V33" />
    <trace from=".J1 > .P17" to="net.V33" />
    <trace from=".J1 > .P1" to="net.V33" />
    <trace from=".J2 > .GND" to="net.GND" />
    <trace from=".J3 > .GND" to="net.GND" />
    <trace from=".J4 > .GND" to="net.GND" />
    <trace from=".J5 > .GND" to="net.GND" />
    <trace from=".J6 > .GND" to="net.GND" />
    <trace from=".J7 > .GND" to="net.GND" />
    <trace from=".J8 > .GND" to="net.GND" />
    <trace from=".J9 > .GND" to="net.GND" />
    <trace from=".J1 > .P9" to="net.GND" />
    <trace from=".J1 > .P20" to="net.GND" />
    <trace from=".J1 > .P6" to="net.GND" />
    <trace from=".J1 > .P14" to="net.GND" />
    <trace from=".J1 > .P25" to="net.GND" />
    <trace from=".J7 > .5V" to="net.V5" />
    <trace from=".J1 > .P4" to="net.V5" />
    <trace from=".C1 > .pin1" to="net.V33" />
    <trace from=".C1 > .pin2" to="net.GND" />
    <trace from=".C2 > .pin1" to="net.V33" />
    <trace from=".C2 > .pin2" to="net.GND" />
    <trace from=".C3 > .pin1" to="net.V33" />
    <trace from=".C3 > .pin2" to="net.GND" />
    <trace from=".C4 > .pin1" to="net.V33" />
    <trace from=".C4 > .pin2" to="net.GND" />
    <trace from=".C5 > .pin1" to="net.V33" />
    <trace from=".C5 > .pin2" to="net.GND" />
    <trace from=".C6 > .pin1" to="net.V5" />
    <trace from=".C6 > .pin2" to="net.GND" />
    <trace from=".C7 > .pin1" to="net.V33" />
    <trace from=".C7 > .pin2" to="net.GND" />
    <trace from=".C8 > .pin1" to="net.V33" />
    <trace from=".C8 > .pin2" to="net.GND" />
    <trace from=".C9 > .pin1" to="net.V33" />
    <trace from=".C9 > .pin2" to="net.GND" />
    <trace from=".C10 > .pin1" to="net.V5" />
    <trace from=".C10 > .pin2" to="net.GND" />
    <trace from=".J4 > .BCLK" to=".J1 > .P12" />
    <trace from=".J4 > .LRCL" to=".J1 > .P35" />
    <trace from=".J4 > .DOUT" to=".J1 > .P38" />
    <trace from=".J6 > .TXD__RXD" to=".J1 > .P10" />
    <trace from=".J6 > .RXD__TXD" to=".J1 > .P8" />
    <trace from=".J6 > .PPS" to=".J1 > .P7" />
    <trace from=".J7 > .TX" to=".J1 > .P33" />
    <trace from=".J7 > .RX" to=".J1 > .P32" />
    <trace from=".J9 > .MOSI" to=".J1 > .P19" />
    <trace from=".J9 > .MISO" to=".J1 > .P21" />
    <trace from=".J9 > .SCLK" to=".J1 > .P23" />
    <trace from=".J9 > .CS" to=".J1 > .P24" />
  </board>
)
