// GENERATED by tools/gen-boards.mjs from schema/hardware.json, do not edit.
//
// Tier 2 - Core carrier: 8 header-connected modules, 36 signals.
//
// This is a reference carrier that has never been fabricated. It exists so the
// pin assignments in the hardware registry are checked by a router rather than
// by a reader. Do not send these outputs to a fab without reviewing them.
//
// Modules on this board:
//   J2  env-bme688       i2c
//   J3  pwr-ina226       i2c
//   J4  mic-ics43434     i2s
//   J5  imu-bno085       i2c
//   J6  gnss-lc29h       uart+gpio
//   J7  radar-ld2450     uart
//   J8  uv-as7331        i2c
//   J9  mag-rm3100       spi
//
// Not on this board: USB peripherals and CSI cameras, which do not touch the
// GPIO header. See schema/hardware.json for the full tier bill of materials.

export default () => (
  <board
    width="115mm"
    height="76mm"
    /* Four layers. Two could not route tier 3's 37 nets, and a carrier with
       this many buses crossing wants an inner ground plane anyway. */
    layers={4}
    /* The default autorouter, capacity-mesh. It used to throw on these
       netlists, and print "Exported!" while doing it, because the CLI runs
       under Bun and Bun 1.1.18 lacks the ES2025 Iterator Helpers its solver
       calls. hardware/iterator-helpers-polyfill.js supplies them via
       bun --preload. Falling back to the sequential router instead had cost
       roughly a quarter of the nets. */
  >
    {/* Raspberry Pi 5 40-pin GPIO header. Pin numbering is physical, matching
        the "pin" field in schema/hardware.json. */}
    {/* Pins are labelled P1..P40 by Raspberry Pi physical number. The
        connector's own numbering is counter-clockwise and does not match; see
        piPinToHeaderIndex in tools/gen-boards.mjs. Everything below references
        the P-labels, never the connector index. */}
    <pinheader
      name="J1"
      pinCount={40}
      gender="male"
      pitch="2.54mm"
      doubleRow
      pinLabels={{"pin1":"P1","pin2":"P2","pin40":"P3","pin3":"P4","pin39":"P5","pin4":"P6","pin38":"P7","pin5":"P8","pin37":"P9","pin6":"P10","pin36":"P11","pin7":"P12","pin35":"P13","pin8":"P14","pin34":"P15","pin9":"P16","pin33":"P17","pin10":"P18","pin32":"P19","pin11":"P20","pin31":"P21","pin12":"P22","pin30":"P23","pin13":"P24","pin29":"P25","pin14":"P26","pin28":"P27","pin15":"P28","pin27":"P29","pin16":"P30","pin26":"P31","pin17":"P32","pin25":"P33","pin18":"P34","pin24":"P35","pin19":"P36","pin23":"P37","pin20":"P38","pin22":"P39","pin21":"P40"}}
      pcbX={-0.87} pcbY={23.23} schX={-9} schY={0}
    />

    {/* env-bme688, Bosch BME688 (i2c) */}
    <pinheader
      name="J2"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-20.32} pcbY={14.23} schX={0} schY={4}
    />
    {/* pwr-ina226, Texas Instruments / generic breakout INA226 bidirectional current and power monitor (i2c) */}
    <pinheader
      name="J3"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-8.16} pcbY={14.23} schX={7} schY={4}
    />
    {/* mic-ics43434, TDK InvenSense ICS-43434 I2S MEMS microphone (i2s) */}
    <pinheader
      name="J4"
      pinCount={5}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"BCLK","pin4":"LRCL","pin5":"DOUT"}}
      pcbX={9.74} pcbY={14.23} schX={14} schY={4}
    />
    {/* imu-bno085, CEVA / Adafruit BNO085 9-DoF IMU (i2c) */}
    <pinheader
      name="J5"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-20.32} pcbY={4.73} schX={0} schY={0}
    />
    {/* gnss-lc29h, Quectel / Waveshare LC29H(DA) RTK HAT with PPS (uart+gpio) */}
    <pinheader
      name="J6"
      pinCount={5}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"TXD__RXD","pin4":"RXD__TXD","pin5":"PPS"}}
      pcbX={-6.89} pcbY={4.73} schX={7} schY={0}
    />
    {/* radar-ld2450, Hi-Link LD2450 24 GHz tracking radar (uart) */}
    <pinheader
      name="J7"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"5V","pin2":"GND","pin3":"TX","pin4":"RX"}}
      pcbX={15.24} pcbY={4.73} schX={14} schY={0}
    />
    {/* uv-as7331, ams OSRAM AS7331 UVA/UVB/UVC sensor (i2c) */}
    <pinheader
      name="J8"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-20.32} pcbY={-4.77} schX={0} schY={-4}
    />
    {/* mag-rm3100, PNI Sensor RM3100 3-axis geomagnetic sensor (spi) */}
    <pinheader
      name="J9"
      pinCount={6}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"MOSI","pin4":"MISO","pin5":"SCLK","pin6":"CS"}}
      pcbX={1.91} pcbY={-4.77} schX={7} schY={-4}
    />

    <net name="SDA" />
    <net name="SCL" />
    <net name="V33" />
    <net name="GND" />
    <net name="V5" />
    <copperpour layer="inner1" connectsTo="net.GND" />
    <hole name="H1" diameter="2.75mm" pcbX={-29} pcbY={-24.5} />
    <hole name="H2" diameter="2.75mm" pcbX={29} pcbY={-24.5} />
    <hole name="H3" diameter="2.75mm" pcbX={-29} pcbY={24.5} />
    <hole name="H4" diameter="2.75mm" pcbX={29} pcbY={24.5} />
    {/* decoupling for J2 (env-bme688) */}
    <capacitor name="C1" capacitance="100nF" footprint="0402"
      pcbX={-19.32} pcbY={10.63} schX={0} schY={2.4} />
    {/* decoupling for J3 (pwr-ina226) */}
    <capacitor name="C2" capacitance="100nF" footprint="0402"
      pcbX={-7.16} pcbY={10.63} schX={7} schY={2.4} />
    {/* decoupling for J4 (mic-ics43434) */}
    <capacitor name="C3" capacitance="100nF" footprint="0402"
      pcbX={10.74} pcbY={10.63} schX={14} schY={2.4} />
    {/* decoupling for J5 (imu-bno085) */}
    <capacitor name="C4" capacitance="100nF" footprint="0402"
      pcbX={-19.32} pcbY={1.13} schX={0} schY={-1.6} />
    {/* decoupling for J6 (gnss-lc29h) */}
    <capacitor name="C5" capacitance="100nF" footprint="0402"
      pcbX={-5.89} pcbY={1.13} schX={7} schY={-1.6} />
    {/* decoupling for J7 (radar-ld2450) */}
    <capacitor name="C6" capacitance="100nF" footprint="0402"
      pcbX={16.24} pcbY={1.13} schX={14} schY={-1.6} />
    {/* decoupling for J8 (uv-as7331) */}
    <capacitor name="C7" capacitance="100nF" footprint="0402"
      pcbX={-19.32} pcbY={-8.37} schX={0} schY={-5.6} />
    {/* decoupling for J9 (mag-rm3100) */}
    <capacitor name="C8" capacitance="100nF" footprint="0402"
      pcbX={2.91} pcbY={-8.37} schX={7} schY={-5.6} />
    {/* bulk reservoir on V33 */}
    <capacitor name="C9" capacitance="10uF" footprint="0805"
      pcbX={-19.00} pcbY={-25.27} schX={-4} schY={-21} />
    {/* bulk reservoir on V5 */}
    <capacitor name="C10" capacitance="10uF" footprint="0805"
      pcbX={-13.00} pcbY={-25.27} schX={-4} schY={-22.5} />
    {/* TVS clamp on SDA, which leaves the enclosure toward
        env-bme688. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D1" footprint="sot23" pcbX={-54.00} pcbY={-19.27}
      schX={0} schY={1.6} />
    {/* TVS clamp on SCL, which leaves the enclosure toward
        env-bme688. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D2" footprint="sot23" pcbX={-48.50} pcbY={-19.27}
      schX={0} schY={1.6} />
    {/* TVS clamp on BCLK, which leaves the enclosure toward
        mic-ics43434. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D3" footprint="sot23" pcbX={-43.00} pcbY={-19.27}
      schX={14} schY={1.6} />
    {/* TVS clamp on LRCL, which leaves the enclosure toward
        mic-ics43434. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D4" footprint="sot23" pcbX={-37.50} pcbY={-19.27}
      schX={14} schY={1.6} />
    {/* TVS clamp on DOUT, which leaves the enclosure toward
        mic-ics43434. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D5" footprint="sot23" pcbX={-32.00} pcbY={-19.27}
      schX={14} schY={1.6} />
    {/* TVS clamp on MOSI, which leaves the enclosure toward
        mag-rm3100. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D6" footprint="sot23" pcbX={-26.50} pcbY={-19.27}
      schX={7} schY={-6.4} />
    {/* TVS clamp on MISO, which leaves the enclosure toward
        mag-rm3100. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D7" footprint="sot23" pcbX={-21.00} pcbY={-19.27}
      schX={7} schY={-6.4} />
    {/* TVS clamp on SCLK, which leaves the enclosure toward
        mag-rm3100. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D8" footprint="sot23" pcbX={-15.50} pcbY={-19.27}
      schX={7} schY={-6.4} />
    {/* TVS clamp on CS, which leaves the enclosure toward
        mag-rm3100. That cable is an antenna on a mast, and its far
        end is outside every protection the box provides. */}
    <diode name="D9" footprint="sot23" pcbX={-10.00} pcbY={-19.27}
      schX={7} schY={-6.4} />
    {/* V33 supply: resettable fuse and reverse-polarity diode. An
        off-grid node is wired by whoever installed it, in the field,
        often in the dark, and battery leads get reversed. */}
    <fuse name="F1" currentRating="2A" footprint="1206"
      pcbX={-4.50} pcbY={-19.27} schX={-6} schY={-9} />
    <diode name="D10" footprint="sod123"
      pcbX={0.50} pcbY={-19.27} schX={-4} schY={-9} />
    {/* V5 supply: resettable fuse and reverse-polarity diode. An
        off-grid node is wired by whoever installed it, in the field,
        often in the dark, and battery leads get reversed. */}
    <fuse name="F2" currentRating="2A" footprint="1206"
      pcbX={6.50} pcbY={-19.27} schX={-6} schY={-11} />
    <diode name="D11" footprint="sod123"
      pcbX={11.50} pcbY={-19.27} schX={-4} schY={-11} />
    {/* HAT ID EEPROM on ID_SD/ID_SC (pins 27 and 28), per the HAT
        specification. Write-protected in normal operation. */}
    <chip name="U1" footprint="soic8"
      pinLabels={{ pin1: "A0", pin2: "A1", pin3: "A2", pin4: "GND", pin5: "SDA", pin6: "SCL", pin7: "WP", pin8: "VCC" }}
      pcbX={23.50} pcbY={-19.27} schX={8} schY={-8} />
    <trace from=".J2 > .SDA" to="net.SDA" />
    <trace from=".J3 > .SDA" to="net.SDA" />
    <trace from=".J5 > .SDA" to="net.SDA" />
    <trace from=".J8 > .SDA" to="net.SDA" />
    <trace from=".J1 > .P3" to="net.SDA" />
    <trace from=".J2 > .SCL" to="net.SCL" />
    <trace from=".J3 > .SCL" to="net.SCL" />
    <trace from=".J5 > .SCL" to="net.SCL" />
    <trace from=".J8 > .SCL" to="net.SCL" />
    <trace from=".J1 > .P5" to="net.SCL" />
    <trace from=".J2 > .3V3" to="net.V33" />
    <trace from=".J3 > .3V3" to="net.V33" />
    <trace from=".J4 > .3V3" to="net.V33" />
    <trace from=".J5 > .3V3" to="net.V33" />
    <trace from=".J6 > .3V3" to="net.V33" />
    <trace from=".J8 > .3V3" to="net.V33" />
    <trace from=".J9 > .3V3" to="net.V33" />
    <trace from=".J1 > .P17" to="net.V33" />
    <trace from=".J1 > .P1" to="net.V33" />
    <trace from=".J2 > .GND" to="net.GND" />
    <trace from=".J3 > .GND" to="net.GND" />
    <trace from=".J4 > .GND" to="net.GND" />
    <trace from=".J5 > .GND" to="net.GND" />
    <trace from=".J6 > .GND" to="net.GND" />
    <trace from=".J7 > .GND" to="net.GND" />
    <trace from=".J8 > .GND" to="net.GND" />
    <trace from=".J9 > .GND" to="net.GND" />
    <trace from=".J1 > .P9" to="net.GND" />
    <trace from=".J1 > .P20" to="net.GND" />
    <trace from=".J1 > .P6" to="net.GND" />
    <trace from=".J1 > .P14" to="net.GND" />
    <trace from=".J1 > .P25" to="net.GND" />
    <trace from=".J7 > .5V" to="net.V5" />
    <trace from=".J1 > .P4" to="net.V5" />
    <trace from=".C1 > .pin1" to="net.V33" />
    <trace from=".C1 > .pin2" to="net.GND" />
    <trace from=".C2 > .pin1" to="net.V33" />
    <trace from=".C2 > .pin2" to="net.GND" />
    <trace from=".C3 > .pin1" to="net.V33" />
    <trace from=".C3 > .pin2" to="net.GND" />
    <trace from=".C4 > .pin1" to="net.V33" />
    <trace from=".C4 > .pin2" to="net.GND" />
    <trace from=".C5 > .pin1" to="net.V33" />
    <trace from=".C5 > .pin2" to="net.GND" />
    <trace from=".C6 > .pin1" to="net.V5" />
    <trace from=".C6 > .pin2" to="net.GND" />
    <trace from=".C7 > .pin1" to="net.V33" />
    <trace from=".C7 > .pin2" to="net.GND" />
    <trace from=".C8 > .pin1" to="net.V33" />
    <trace from=".C8 > .pin2" to="net.GND" />
    <trace from=".C9 > .pin1" to="net.V33" />
    <trace from=".C9 > .pin2" to="net.GND" />
    <trace from=".C10 > .pin1" to="net.V5" />
    <trace from=".C10 > .pin2" to="net.GND" />
    <trace from=".D1 > .pin1" to="net.GND" />
    <trace from=".D1 > .pin2" to="net.SDA" />
    <trace from=".D2 > .pin1" to="net.GND" />
    <trace from=".D2 > .pin2" to="net.SCL" />
    <trace from=".D3 > .pin1" to="net.GND" />
    <trace from=".D3 > .pin2" to=".J4 > .BCLK" />
    <trace from=".D4 > .pin1" to="net.GND" />
    <trace from=".D4 > .pin2" to=".J4 > .LRCL" />
    <trace from=".D5 > .pin1" to="net.GND" />
    <trace from=".D5 > .pin2" to=".J4 > .DOUT" />
    <trace from=".D6 > .pin1" to="net.GND" />
    <trace from=".D6 > .pin2" to=".J9 > .MOSI" />
    <trace from=".D7 > .pin1" to="net.GND" />
    <trace from=".D7 > .pin2" to=".J9 > .MISO" />
    <trace from=".D8 > .pin1" to="net.GND" />
    <trace from=".D8 > .pin2" to=".J9 > .SCLK" />
    <trace from=".D9 > .pin1" to="net.GND" />
    <trace from=".D9 > .pin2" to=".J9 > .CS" />
    <trace from=".F1 > .pin1" to="net.V33" />
    <trace from=".D10 > .pin1" to="net.GND" />
    <trace from=".F2 > .pin1" to="net.V5" />
    <trace from=".D11 > .pin1" to="net.GND" />
    <trace from=".U1 > .SDA" to=".J1 > .P27" />
    <trace from=".U1 > .SCL" to=".J1 > .P28" />
    <trace from=".U1 > .VCC" to="net.V33" />
    <trace from=".U1 > .GND" to="net.GND" />
    <trace from=".U1 > .WP" to="net.V33" />
    <trace from=".J4 > .BCLK" to=".J1 > .P12" />
    <trace from=".J4 > .LRCL" to=".J1 > .P35" />
    <trace from=".J4 > .DOUT" to=".J1 > .P38" />
    <trace from=".J6 > .TXD__RXD" to=".J1 > .P10" />
    <trace from=".J6 > .RXD__TXD" to=".J1 > .P8" />
    <trace from=".J6 > .PPS" to=".J1 > .P7" />
    <trace from=".J7 > .TX" to=".J1 > .P33" />
    <trace from=".J7 > .RX" to=".J1 > .P32" />
    <trace from=".J9 > .MOSI" to=".J1 > .P19" />
    <trace from=".J9 > .MISO" to=".J1 > .P21" />
    <trace from=".J9 > .SCLK" to=".J1 > .P23" />
    <trace from=".J9 > .CS" to=".J1 > .P24" />
  </board>
)
