// GENERATED by tools/gen-boards.mjs from schema/hardware.json — do not edit.
//
// Tier 3 - Extended carrier: 8 header-connected modules, 37 signals.
//
// This is a reference carrier that has never been fabricated. It exists so the
// pin assignments in the hardware registry are checked by a router rather than
// by a reader. Do not send these outputs to a fab without reviewing them.
//
// Modules on this board:
//   J2  gnss-lc29h       uart+gpio
//   J3  env-bme688       i2c
//   J4  imu-bno085       i2c
//   J5  uv-as7331        i2c
//   J6  mag-rm3100       spi
//   J7  mic-ics43434     i2s
//   J8  seis-sm24        adc
//   J9  sem-ir-beacon    gpio+pwm
//
// Not on this board: USB peripherals and CSI cameras, which do not touch the
// GPIO header. See schema/hardware.json for the full tier bill of materials.

export default () => (
  <board
    width="65mm"
    height="56mm"
    /* Four layers. Two could not route tier 3's 37 nets, and a carrier with
       this many buses crossing wants an inner ground plane anyway. */
    layers={4}
    /* The default capacity-mesh autorouter throws on this netlist in the
       currently pinned CLI, and does so while the export still reports
       success. Pinned to the sequential router, and tools/check-boards.mjs
       fails the build if the trace count ever comes back short. */
    autorouter="sequential-trace"
  >
    {/* Raspberry Pi 5 40-pin GPIO header. Pin numbering is physical, matching
        the "pin" field in schema/hardware.json. */}
    <pinheader
      name="J1"
      pinCount={40}
      gender="male"
      pitch="2.54mm"
      doubleRow
      pcbX={0} pcbY={-21} schX={-9} schY={0}
    />

    {/* gnss-lc29h — Quectel / Waveshare LC29H(DA) RTK HAT with PPS (uart+gpio) */}
    <pinheader
      name="J2"
      pinCount={5}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"TXD__RXD","pin4":"RXD__TXD","pin5":"PPS"}}
      pcbX={-19} pcbY={20} schX={0} schY={4}
    />
    {/* env-bme688 — Bosch BME688 (i2c) */}
    <pinheader
      name="J3"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={15} pcbY={20} schX={7} schY={4}
    />
    {/* imu-bno085 — CEVA / Adafruit BNO085 9-DoF IMU (i2c) */}
    <pinheader
      name="J4"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={-19} pcbY={10} schX={0} schY={0}
    />
    {/* uv-as7331 — ams OSRAM AS7331 UVA/UVB/UVC sensor (i2c) */}
    <pinheader
      name="J5"
      pinCount={4}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"SDA","pin4":"SCL"}}
      pcbX={15} pcbY={10} schX={7} schY={0}
    />
    {/* mag-rm3100 — PNI Sensor RM3100 3-axis geomagnetic sensor (spi) */}
    <pinheader
      name="J6"
      pinCount={6}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"MOSI","pin4":"MISO","pin5":"SCLK","pin6":"CS"}}
      pcbX={-19} pcbY={0} schX={0} schY={-4}
    />
    {/* mic-ics43434 — TDK InvenSense ICS-43434 I2S MEMS microphone (i2s) */}
    <pinheader
      name="J7"
      pinCount={5}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"BCLK","pin4":"LRCL","pin5":"DOUT"}}
      pcbX={15} pcbY={0} schX={7} schY={-4}
    />
    {/* seis-sm24 — ION / Sercel SM-24 geophone element (adc) */}
    <pinheader
      name="J8"
      pinCount={6}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"3V3","pin2":"GND","pin3":"MOSI","pin4":"MISO","pin5":"SCLK","pin6":"CS"}}
      pcbX={-19} pcbY={-10} schX={0} schY={-8}
    />
    {/* sem-ir-beacon — generic 850 nm pulsed IR beacon, 5 W peak (gpio+pwm) */}
    <pinheader
      name="J9"
      pinCount={3}
      gender="female"
      pitch="2.54mm"
      pinLabels={{"pin1":"5V","pin2":"GND","pin3":"GATE"}}
      pcbX={15} pcbY={-10} schX={7} schY={-8}
    />

    <net name="V33" />
    <net name="GND" />
    <net name="V5" />
    <trace from=".J2 > .3V3" to="net.V33" />
    <trace from=".J3 > .3V3" to="net.V33" />
    <trace from=".J4 > .3V3" to="net.V33" />
    <trace from=".J5 > .3V3" to="net.V33" />
    <trace from=".J6 > .3V3" to="net.V33" />
    <trace from=".J7 > .3V3" to="net.V33" />
    <trace from=".J8 > .3V3" to="net.V33" />
    <trace from=".J1 > .pin1" to="net.V33" />
    <trace from=".J1 > .pin17" to="net.V33" />
    <trace from=".J2 > .GND" to="net.GND" />
    <trace from=".J3 > .GND" to="net.GND" />
    <trace from=".J4 > .GND" to="net.GND" />
    <trace from=".J5 > .GND" to="net.GND" />
    <trace from=".J6 > .GND" to="net.GND" />
    <trace from=".J7 > .GND" to="net.GND" />
    <trace from=".J8 > .GND" to="net.GND" />
    <trace from=".J9 > .GND" to="net.GND" />
    <trace from=".J1 > .pin6" to="net.GND" />
    <trace from=".J1 > .pin9" to="net.GND" />
    <trace from=".J1 > .pin25" to="net.GND" />
    <trace from=".J1 > .pin20" to="net.GND" />
    <trace from=".J1 > .pin39" to="net.GND" />
    <trace from=".J1 > .pin30" to="net.GND" />
    <trace from=".J9 > .5V" to="net.V5" />
    <trace from=".J1 > .pin2" to="net.V5" />
    <trace from=".J2 > .TXD__RXD" to=".J1 > .pin10" />
    <trace from=".J2 > .RXD__TXD" to=".J1 > .pin8" />
    <trace from=".J2 > .PPS" to=".J1 > .pin7" />
    <trace from=".J3 > .SDA" to=".J1 > .pin3" />
    <trace from=".J3 > .SCL" to=".J1 > .pin5" />
    <trace from=".J4 > .SDA" to=".J1 > .pin3" />
    <trace from=".J4 > .SCL" to=".J1 > .pin5" />
    <trace from=".J5 > .SDA" to=".J1 > .pin3" />
    <trace from=".J5 > .SCL" to=".J1 > .pin5" />
    <trace from=".J6 > .MOSI" to=".J1 > .pin19" />
    <trace from=".J6 > .MISO" to=".J1 > .pin21" />
    <trace from=".J6 > .SCLK" to=".J1 > .pin23" />
    <trace from=".J6 > .CS" to=".J1 > .pin24" />
    <trace from=".J7 > .BCLK" to=".J1 > .pin12" />
    <trace from=".J7 > .LRCL" to=".J1 > .pin35" />
    <trace from=".J7 > .DOUT" to=".J1 > .pin38" />
    <trace from=".J8 > .MOSI" to=".J1 > .pin19" />
    <trace from=".J8 > .MISO" to=".J1 > .pin21" />
    <trace from=".J8 > .SCLK" to=".J1 > .pin23" />
    <trace from=".J8 > .CS" to=".J1 > .pin26" />
    <trace from=".J9 > .GATE" to=".J1 > .pin16" />
  </board>
)
