import { FlatCompat } from '@eslint/eslintrc'
import { dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

/**
 * Flat config, run through the ESLint CLI rather than `next lint`.
 *
 * `next lint` is deprecated in Next 15 and, with no config present, drops into
 * an interactive setup prompt. The lint script therefore linted nothing and
 * would have hung CI the first time it ran there.
 */
export default [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      // Emitted by tools/codegen.mjs; fix the generator, not the output.
      'lib/schema/generated.ts',
      'lib/schema/constants.mjs',
      'lib/search-index.json',
      // Generated by Next on every build.
      'next-env.d.ts',
    ],
  },
  {
    rules: {
      // The discriminator port is deliberately plain JavaScript so the parity
      // check can run it under bare node; it carries no type annotations.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
]
